name: Dictav Site
pygments: true
markdown: redcarpet
redcarpet:
   extensions: ['no_intra_emphasis', 'autolink', 'strikethrough', 'superscript']
author:
   name: dictav
   email: dictav at gmail.com
paginate: 10
paginate_path: "blog/page:num"
